<a href="https://colab.research.google.com/github/charan0887/ML_LAB_2026-27/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.


NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.



**Why Use Numpy**

In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.


Numpy arrays are optimized for complex mathematical and statistical operations. Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

**Import NumPy in Python**

In [7]:
import numpy as np

**NumPy Array Creation**

In [8]:

list = [1, 2, 3, 4]


array1 = np.array(list)

print(array1)

[1 2 3 4]


Instead of creating a list and using the list variable with the np.array() function, we can directly pass list elements as an argument.

In [9]:

array1 = np.array([1, 2, 3, 4])
print(array1)

[1 2 3 4]


**Create a 2-D NumPy Array**

In [10]:

array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


**Create a 3-D NumPy Array**

In [11]:

array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Check Data Type of a NumPy Array**

In [13]:

array1 = np.array([2, 4, 6, 8])

print(array1.dtype)

int64


**Check dimensions of an Numpy Array**

In [14]:
print(array1.ndim)

1


**Check Size of Numpy array**

In [15]:
print(array1.size)

4


**NumPy Array shape Attribute**

In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension.

In [18]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8],
                [4, 5, 9]])

print(array1.shape)

(3, 3)


**NumPy Array itemsize Attribute**

In NumPy, the itemsize attribute determines size (in bytes) of each element in the array.

In [34]:

array1 = np.array([6, 7, 8, 10 ])


array2 = np.array([6, 7, 8, 10 ], dtype=np.int64)
print(array1.itemsize)
print(array2.itemsize)

8
8


**NumPy Array data Attribute**

In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

In simpler terms, the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

In [22]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])


print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7e788cb065c0>
Data of array2 is:  <memory at 0x7e788c079be0>


**Access Array Elements Using Index**

In [ ]:
array1 = np.array([1, 3, 5, 7, 9])


print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


**Modify Array Elements Using Index**

In [25]:
array1[2]=6
print(array1)

[6 7 6]


**2-D NumPy Array Indexing**

In [36]:
# create a 2D array
array1 = np.array([[0, 2, 4, 56, 43],
                       [9342, 112, 153, 185,43],
                       [25, 465, 622, 812,54]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 185
2nd Element at First Row: 2


**NumPy Statistical Functions**

Functions

median()	return the median of an array

mean()	return the mean of an array

std()	return the standard deviation of an array

percentile()	return the nth percentile of elements in an array

min()	return the minimum element of an array

max()	return the maximum element of an array

In [ ]:
# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)

3.0


**Compute Mean Using NumPy**

In [35]:
# create a numpy array
marks = np.array([94, 72, 87, 61, 80])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)

78.8


**Standard Deviation of NumPy Array**

In [ ]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


**Numpy Percentile**

In [ ]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)

78.0


**Numpy min**

In [ ]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)

66


**Numpy max**

In [ ]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)

85
